create table if not exists films (
    id bigint generated by default as identity primary key,
    name nvarchar(255),
    description nvarchar(255),
    release_date date,
    duration integer,
    genre integer,
    mpa integer
);
create table if not exists users (
    id bigint generated by default as identity primary key,
    name nvarchar(255),
    email nvarchar(255),
    login nvarchar(255),
    birthday date
);
create table if not exists friendship (
    user_id integer,
    friend_id integer,
    status nvarchar(255)
);
create table if not exists likes (
    user_id integer,
    film_id integer
);
create table if not exists genres (
    id integer primary key,
    name nvarchar(255)
);
create table if not exists mpa (
    id integer primary key,
    name nvarchar(255),
    description nvarchar(255)
);


